[package]
name = "payment_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
rust_decimal ={ version = "1.0.0", features = ["serde"]}
rust_decimal_macros = "1.39.0"
serde = {version = "1.0.228", features = ["derive"]}

